apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.grafana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.name }}
    spec:
      containers:
      - name: {{ .Values.grafana.name }}
        image: {{ .Values.grafana.image }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.grafana.name }}
  ports:
  - port: 3000
    targetPort: 3000
