apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
      containers:
      - name: {{ .Values.prometheus.name }}
        image: {{ .Values.prometheus.image }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.prometheus.name }}
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    rule_files:
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "helloworld_health"
        static_configs:
          - targets: ["helloworld:80"]
